insert into Blood_Data (BID, BloodType, Disease) values ('46987', 'b-', 'low T count');
insert into Blood_Data (BID, BloodType, Disease) values ('97995', 'o-', 'sickle cell');
insert into Blood_Data (BID, BloodType, Disease) values ('88468', 'o+', 'perfect');
insert into Blood_Data (BID, BloodType, Disease) values ('63130', 'o+', 'low T count');
insert into Blood_Data (BID, BloodType, Disease) values ('51328', 'a-', 'low T count');
insert into Blood_Data (BID, BloodType, Disease) values ('79304', 'a-', 'low T count');
insert into Blood_Data (BID, BloodType, Disease) values ('65806', 'o+', 'perfect');
insert into Blood_Data (BID, BloodType, Disease) values ('51699', 'o+', 'low T count');
insert into Blood_Data (BID, BloodType, Disease) values ('25892', 'a-', 'low T count');
insert into Blood_Data (BID, BloodType, Disease) values ('70042', 'o-', 'perfect');
insert into Blood_Data (BID, BloodType, Disease) values ('64318', 'ab+', 'perfect');
insert into Blood_Data (BID, BloodType, Disease) values ('15836', 'o-', 'perfect');
insert into Blood_Data (BID, BloodType, Disease) values ('81255', 'b-', 'sickle cell');
insert into Blood_Data (BID, BloodType, Disease) values ('94734', 'b-', 'perfect');
insert into Blood_Data (BID, BloodType, Disease) values ('92746', 'a-', 'low T count');
insert into Blood_Data (BID, BloodType, Disease) values ('22315', 'ab-', 'perfect');
insert into Blood_Data (BID, BloodType, Disease) values ('57253', 'o-', 'sickle cell');
insert into Blood_Data (BID, BloodType, Disease) values ('15979', 'b-', 'sickle cell');
insert into Blood_Data (BID, BloodType, Disease) values ('86962', 'o+', 'low T count');
insert into Blood_Data (BID, BloodType, Disease) values ('95903', 'b+', 'low T count');
insert into Blood_Data (BID, BloodType, Disease) values ('98062', 'ab-', 'low T count');
insert into Blood_Data (BID, BloodType, Disease) values ('95744', 'o-', 'sickle cell');
insert into Blood_Data (BID, BloodType, Disease) values ('48208', 'o+', 'sickle cell');
insert into Blood_Data (BID, BloodType, Disease) values ('53270', 'b-', 'perfect');
insert into Blood_Data (BID, BloodType, Disease) values ('26493', 'a+', 'low T count');
insert into Blood_Data (BID, BloodType, Disease) values ('27866', 'o-', 'low T count');
insert into Blood_Data (BID, BloodType, Disease) values ('28267', 'a+', 'low T count');
insert into Blood_Data (BID, BloodType, Disease) values ('86997', 'a-', 'low T count');
insert into Blood_Data (BID, BloodType, Disease) values ('62104', 'o-', 'low T count');
insert into Blood_Data (BID, BloodType, Disease) values ('92689', 'b+', 'perfect');
insert into Blood_Data (BID, BloodType, Disease) values ('27510', 'a+', 'perfect');
insert into Blood_Data (BID, BloodType, Disease) values ('45107', 'a-', 'low T count');
insert into Blood_Data (BID, BloodType, Disease) values ('84762', 'ab-', 'sickle cell');
insert into Blood_Data (BID, BloodType, Disease) values ('16628', 'ab+', 'sickle cell');
insert into Blood_Data (BID, BloodType, Disease) values ('81048', 'o-', 'sickle cell');
insert into Blood_Data (BID, BloodType, Disease) values ('59230', 'a-', 'sickle cell');
insert into Blood_Data (BID, BloodType, Disease) values ('24402', 'b-', 'perfect');
insert into Blood_Data (BID, BloodType, Disease) values ('21031', 'ab-', 'sickle cell');
insert into Blood_Data (BID, BloodType, Disease) values ('98115', 'ab-', 'perfect');
insert into Blood_Data (BID, BloodType, Disease) values ('15782', 'a-', 'low T count');
insert into Blood_Data (BID, BloodType, Disease) values ('10294', 'ab-', 'perfect');
insert into Blood_Data (BID, BloodType, Disease) values ('48198', 'b+', 'sickle cell');
insert into Blood_Data (BID, BloodType, Disease) values ('59873', 'o-', 'perfect');
insert into Blood_Data (BID, BloodType, Disease) values ('99266', 'a+', 'low T count');
insert into Blood_Data (BID, BloodType, Disease) values ('14002', 'b-', 'sickle cell');
insert into Blood_Data (BID, BloodType, Disease) values ('27016', 'o+', 'low T count');
insert into Blood_Data (BID, BloodType, Disease) values ('49213', 'ab-', 'perfect');
insert into Blood_Data (BID, BloodType, Disease) values ('41185', 'a+', 'sickle cell');
insert into Blood_Data (BID, BloodType, Disease) values ('83233', 'b-', 'sickle cell');
insert into Blood_Data (BID, BloodType, Disease) values ('17750', 'o+', 'perfect');
