insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Thompson LLC', '5328 Dapin Circle', '182-112-9008', 'Glynn Laurenson');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Leuschke-Lynch', '57795 Maple Wood Crossing', '679-883-8087', 'Amalie Graeber');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Johnston LLC', '69 Mayer Terrace', '281-516-2432', 'Jeniffer Stubbes');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('West, Moen and Eichmann', '87895 Clarendon Circle', '500-195-3178', 'Anett Zealy');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('O''Hara LLC', '49 Lukken Alley', '453-509-2292', 'Adriena Bisiker');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Hayes-Bogan', '1 Sutherland Circle', '149-652-3350', 'Binnie Sterndale');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Brakus, Green and Graham', '2 Miller Parkway', '348-378-3223', 'marianne magovern');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Schoen LLC', '92985 Fairfield Plaza', '671-275-0083', 'Cora Rumble');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Koss, Kulas and Spinka', '7 Portage Hill', '193-102-6120', 'Sal Maddaford');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Medhurst, Beer and Mohr', '6 Forest Dale Parkway', '790-445-0761', 'Aldo Brayshaw');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Thompson LLC', '5328 Dapin Circle', '182-112-9008', 'Elyn Prop');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Leuschke-Lynch', '57795 Maple Wood Crossing', '679-883-8087', 'Kenny Renshall');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Johnston LLC', '69 Mayer Terrace', '281-516-2432', 'Shandy Stovold');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('West, Moen and Eichmann', '87895 Clarendon Circle', '500-195-3178', 'Marnie Maclardie');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('O''Hara LLC', '49 Lukken Alley', '453-509-2292', 'Margit Goodale');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Hayes-Bogan', '1 Sutherland Circle', '149-652-3350', 'Melisande Aucock');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Brakus, Green and Graham', '2 Miller Parkway', '348-378-3223', 'Ezmeralda Stoll');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Schoen LLC', '92985 Fairfield Plaza', '671-275-0083', 'Gus Adrian');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Koss, Kulas and Spinka', '7 Portage Hill', '193-102-6120', 'Eartha Kincade');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Medhurst, Beer and Mohr', '6 Forest Dale Parkway', '790-445-0761', 'Jasmina Whitwood');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Thompson LLC', '5328 Dapin Circle', '182-112-9008', 'Britteny De Coursey');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Leuschke-Lynch', '57795 Maple Wood Crossing', '679-883-8087', 'Allen Metcalfe');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Johnston LLC', '69 Mayer Terrace', '281-516-2432', 'Griselda Chappell');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('West, Moen and Eichmann', '87895 Clarendon Circle', '500-195-3178', 'Ruthie Pidgley');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('O''Hara LLC', '49 Lukken Alley', '453-509-2292', 'Chrysa Mustoo');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Hayes-Bogan', '1 Sutherland Circle', '149-652-3350', 'Alva Schmidt');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Brakus, Green and Graham', '2 Miller Parkway', '348-378-3223', 'Amitie Lalevee');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Schoen LLC', '92985 Fairfield Plaza', '671-275-0083', 'Tami Benion');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Koss, Kulas and Spinka', '7 Portage Hill', '193-102-6120', 'Danila Heazel');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Medhurst, Beer and Mohr', '6 Forest Dale Parkway', '790-445-0761', 'Abraham Deschelle');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Thompson LLC', '5328 Dapin Circle', '182-112-9008', 'Desiree Scinelli');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Leuschke-Lynch', '57795 Maple Wood Crossing', '679-883-8087', 'Editha Jobe');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Johnston LLC', '69 Mayer Terrace', '281-516-2432', 'Madelin Blinerman');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('West, Moen and Eichmann', '87895 Clarendon Circle', '500-195-3178', 'Serena Brack');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('O''Hara LLC', '49 Lukken Alley', '453-509-2292', 'Guntar Ollerhead');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Hayes-Bogan', '1 Sutherland Circle', '149-652-3350', 'Faith Richards');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Brakus, Green and Graham', '2 Miller Parkway', '348-378-3223', 'Yvon Attrey');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Schoen LLC', '92985 Fairfield Plaza', '671-275-0083', 'Alfie Vesty');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Koss, Kulas and Spinka', '7 Portage Hill', '193-102-6120', 'Rolfe Spellesy');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Medhurst, Beer and Mohr', '6 Forest Dale Parkway', '790-445-0761', 'Caty Godard');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Thompson LLC', '5328 Dapin Circle', '182-112-9008', 'Berta Neeson');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Leuschke-Lynch', '57795 Maple Wood Crossing', '679-883-8087', 'Ermina Otson');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Johnston LLC', '69 Mayer Terrace', '281-516-2432', 'Christin Livezley');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('West, Moen and Eichmann', '87895 Clarendon Circle', '500-195-3178', 'Boycie Iamittii');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('O''Hara LLC', '49 Lukken Alley', '453-509-2292', 'Thornton Aphale');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Hayes-Bogan', '1 Sutherland Circle', '149-652-3350', 'Halsey Hanington');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Brakus, Green and Graham', '2 Miller Parkway', '348-378-3223', 'Anestassia Caesmans');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Schoen LLC', '92985 Fairfield Plaza', '671-275-0083', 'Germaine Mulcaster');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Koss, Kulas and Spinka', '7 Portage Hill', '193-102-6120', 'Rudiger Feaver');
insert into Blood_Bank (BloodBank, Address, PhoneNumber, DonorNames) values ('Medhurst, Beer and Mohr', '6 Forest Dale Parkway', '790-445-0761', 'Evonne Binnall');